cmake_minimum_required(VERSION 3.17)
project(DictionaryTree)

set(CMAKE_CXX_STANDARD 17)
include_directories(util)
add_executable(DictionaryTree main.cpp util/util.h test_factory.h L14_longestCommonPrefix/L14_longestCommonPrefix.cpp L14_longestCommonPrefix/L14_longestCommonPrefix.h L139_wordBreak/L139_wordBreak.cpp L139_wordBreak/L139_wordBreak.h L140_wordBreak/L140_wordBreak.cpp L140_wordBreak/L140_wordBreak.h L208_implementTrie/L208_implememtTrie.cpp L208_implementTrie/L208_implememtTrie.h L211_WordDictionary/L211_WordDictionary.cpp L211_WordDictionary/L211_WordDictionary.h L212_findWords/L212_findWords.cpp L212_findWords/L212_findWords.h)